"""Embed the fixed GLSL programs for the native libplacebo build."""
import json
from pathlib import Path
root=Path(__file__).parent
names=['pyramid','features','track','consensus','weights','sample']
text='/* Generated by embed.py from the adjacent GLSL sources. */\n'
for name in names:
    text+=f'static const char cm_{name}_glsl[] =\n'
    text+='\n'.join(json.dumps(line+'\n') for line in (root/(name+'.glsl')).read_text().splitlines())+';\n'
    if name == 'track':
        text+='static const char cm_track_reverse_glsl[] = "#define REVERSE_TRACK\\n"\n'
        text+='\n'.join(json.dumps(line+'\n') for line in (root/'track.glsl').read_text().splitlines())+';\n'
(root/'camera_motion_shaders.h').write_text(text)
